### ISSUE TITLE
Error on start 

### ISSUE THREAD

**Issue by OrixBruno** [DavidVollmers/doki#4]
![image](https://github.com/DavidVollmers/doki/assets/12201411/f346a97a-bcbf-4863-8009-0a9dd8d5b6bd)

Hello guys!!

Help me!!

On execute application with doki, i have this error, can you help me?

This is bug on loading libraries .net sdks.

**Comment by DavidVollmers** [comment]
Can you please post the contents of the `sdk8.csproj` file here?

**Comment by DavidVollmers** [comment]
I will close this issue because of inactivity...
